export declare function FreeImage_OpenMemory(...args:any[]):any//freeimage
export declare function FreeImage_LoadFromMemory(...args:any[]):any//freeimage
export declare function FreeImage_GetWidth(...args:any[]):any//freeimage
export declare function FreeImage_GetHeight(...args:any[]):any//freeimage
export declare function FreeImage_GetBits(...args:any[]):any//freeimage
export declare function FreeImage_ConvertTo32Bits(...args:any[]):any//freeimage
export declare function FreeImage_GetFormatFromFIF(...args:any[]):any//freeimage
export declare function FreeImage_LoadFromHandle(...args:any[]):any//freeimage
export declare function FreeImage_Initialise(...args:any[]):any//freeimage
export declare function FreeImage_Load(...args:any[]):any//freeimage
export declare function FreeImage_GetFileType(...args:any[]):any//freeimage
export declare function FreeImage_GetFileTypeFromMemory(...args:any[]):any//freeimage
export declare function FreeImage_LoadFromMemory(...args:any[]):any//freeimage
export declare function FreeImage_DeInit(...args:any[]):any//freeimage
export declare function FreeImage_Unload(...args:any[]):any//freeimage